# Generated by Django 5.0rc1 on 2023-12-19 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="data",
            new_name="date",
        ),
    ]
